import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    root: {
        flex: 1,
    },
    formulario: {
        flex: 1,
        flexGrow: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
        backgroundColor: '#f5f5f5',
    },
    containerInterno: {
        width: '90%',
        maxWidth: 350,
        backgroundColor: '#fff',
        padding: 30,
        borderRadius: 12,
        shadowColor: '#000',
        marginBottom: 24,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 24,
        color: '#333',
    },
    label: {
        fontSize: 15,
        marginBottom: 6,
        fontWeight: '600',
        color: '#555',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        backgroundColor: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 16,
        fontSize: 16,
        color: '#888888',
    },
    inputFocus: {
        borderColor: '#4a90e2',
    },
    button: {
        width: '100%',
        backgroundColor: '#4a90e2',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    link: {
        marginTop: 16,
        textAlign: 'center',
        color: '#4a90e2',
        fontWeight: '500',
        fontSize: 14,
    },
    tableContainer: {
        width: '100%',
        maxWidth: 500,
        alignSelf: 'center',
        paddingHorizontal: 0,
        marginTop: 8,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#eaf1fb',
        borderRadius: 6,
        paddingVertical: 6,
        paddingHorizontal: 2,
        marginBottom: 2,
    },
    tableHeaderCell: {
        flex: 1,
        fontWeight: 'bold',
        color: '#4a90e2',
        fontSize: 13,
        textAlign: 'center',
        paddingHorizontal: 2,
    },
    tableRow: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 6,
        paddingVertical: 6,
        paddingHorizontal: 2,
        marginBottom: 3,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 2,
        elevation: 1,
    },
    tableCell: {
        flex: 1,
        fontSize: 12,
        color: '#333',
        textAlign: 'center',
        paddingHorizontal: 2,
    },
    tableActions: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionBtn: {
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 5,
        alignItems: 'center',
    },
    actionBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 11,
    },
});