import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    formulario: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        flexGrow: 1,
    },
    containerInterno: {
        width: '90%',
        maxWidth: 350,
        backgroundColor: '#ffffff',
        padding: 30,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    logo: {
        width: 100,
        height: 100,
        borderRadius: 20,
        alignSelf: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 24,
        color: '#333',
    },
    label: {
        fontSize: 15,
        marginBottom: 6,
        fontWeight: '600',
        color: '#555',
    },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        backgroundColor: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 16,
        fontSize: 16,
        color: '#888888',
    },
    inputFocus: {
        borderColor: '#4a90e2',
    },
    button: {
        width: '100%',
        backgroundColor: '#4a90e2',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    link: {
        marginTop: 16,
        textAlign: 'center',
        color: '#4a90e2',
        fontWeight: '500',
        fontSize: 14,
    },
});