import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    root: {
        flex: 1,
    },
    formulario: {
        flex: 1,
        flexGrow: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
        backgroundColor: '#f5f5f5',
    },
    containerInterno: {
        width: '90%',
        maxWidth: 350,
        backgroundColor: '#ffffff',
        padding: 30,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    logo: {
        width: 100,
        height: 100,
        borderRadius: 20,
        alignSelf: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 24,
        color: '#333',
    },
    label: {
        fontSize: 15,
        marginBottom: 6,
        fontWeight: '600',
        color: '#555',
    },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        backgroundColor: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 16,
        fontSize: 16,
        color: '#888888',
    },
    inputFocus: {
        borderColor: '#4a90e2',
    },
    button: {
        width: '100%',
        backgroundColor: '#4a90e2',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    link: {
        marginTop: 16,
        textAlign: 'center',
        color: '#4a90e2',
        fontWeight: '500',
        fontSize: 14,
    },
    inputPasswordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
    },
    iconPassword: {
        position: 'absolute',
        right: 10,
        top: 11,
    },
        loginForm: {
        backgroundColor: '#f7fafd',
        borderRadius: 16,
        padding: 12,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 4,
    },
    loginContainer: {
        paddingTop: 24,
    },
    loginButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#007AFF',
        shadowColor: '#007AFF',
        shadowOpacity: 0.18,
        shadowRadius: 6,
        elevation: 3,
        marginTop: 12,
        marginBottom: 8,
        borderRadius: 8,
        paddingVertical: 12,
    },
    loginButtonText: {
        fontWeight: 'bold',
        fontSize: 17,
    },
    loginLink: {
        color: '#007AFF',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 15,
        marginTop: 10,
    },
    loginFooter: {
        alignItems: 'center',
        marginTop: 24,
    },
    loginFooterText: {
        color: '#888',
        fontSize: 13,
        textAlign: 'center',
    },
});